### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [ComboStrap/stale#1]
When I click on an image of a wiki page, the media file with its detail page is not displayed. Instead, I get an HTTP ERROR 500 error message (Firefox: blank page).

And when I try to load the media manager in edit mode of a wiki page, the media manager window remains empty as well.

Disabling the plugin solves the problem.

One more hint: In my test wiki (Xampp) I get another error message:
`Fatal error: Cannot declare class dokuwiki\Menu\Item\AbstractItem, because the name is already in use in C:\xampp\htdocs\wiki\lib\tpl\bootstrap3\compat\inc\Menu\Item\AbstractItem.php on line 20`

**Comment by gerardnico** [comment]
Which plugin are talking about ? Stale ?

The fatal error comes from `tpl\bootstrap3`  which is the [bootstrap 3](https://www.dokuwiki.org/template:bootstrap3) template.

You can see the [bootstrap3 code line 20](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/blob/master/compat/inc/Menu/Item/AbstractItem.php#L20), just create the [abstract item](https://github.com/splitbrain/dokuwiki/blob/master/inc/Menu/Item/AbstractItem.php) again. Why ? I don't know.

I didn't create `AbstractItem` at all. I use it only at [menuitem](https://github.com/ComboStrap/stale/blob/main/Menuitem.php).
I don't see then how I could create an error. This is just may be because you add a menu item with this plugin.

Do you have other plugin that creates an item in the menu ?

**Comment by gerardnico** [comment]
If you delete the [Menuitem.php file](https://github.com/ComboStrap/stale/blob/main/Menuitem.php), it works?

**Comment by Juergen-aus-Zuendorf** [comment]
Your hint that the error comes in combination with bootstrap was quite good. If I switch to another template, everything works fine. But I think bootstrap is very popular, and in my opinion it would not be bad if your plugin would work together with bootstrap.

Without menuitem.php there comes an error message and wiki is broken.

**Comment by gerardnico** [comment]
I understand but I can't fix the error because it's not in our code and there is no workaround. 
The bootstrap template should not load this class twice and I really can't avoid that.
You should open an issue to this template.

If you are in Bootstrap, you may also try another one :) our Bootstrap theme.
https://combostrap.com/

This plugin was taken over from the dead plugin `toucher`
https://github.com/anandr/dokuwiki-plugin-toucher/pull/2#issuecomment-809981442
You may also try this one.

**Comment by gerardnico** [comment]
To be more precise, making it work for the Boostrap3 template would delete the button functionality in the menu and it would be a regression for other users that would also complain.

**Comment by Juergen-aus-Zuendorf** [comment]
This would not be so good, because the plugin is just easy to call through this button in the bootstrap template
