### ISSUE TITLE
Error 500 on toolbar popup pages like media manager

### ISSUE THREAD

**Issue by bradgillap** [ComboStrap/stale#3]
Hello,

hogfather.

I've managed to determine this plugin is causing me to have internal 500 errors on the popup windows that come from the toolbar. 

Seems to affect popup window from the icons plugin by the bootstrap3 guy and the media manager popout.

I dug around the debug logs, the server error logs, and I'm not finding anything particularly useful either.  I don't know if this is caused by interaction with some of my other plugins. 

EDIT: I see this is a problem with bootstrap3 and this plugin in your issue history and it's marked a won't fix.  Alright thanks, it's definitely a needed plugin for dokuwiki and that's too bad.  

I wonder if there is a chance to get giterlizzi to fix whatever is causing it. You should reach out.. I'd do it but I wouldn't be able to describe it well enough.

https://github.com/giterlizzi/dokuwiki-template-bootstrap3

**Comment by gerardnico** [comment]
Yeah. 

this is an issue caused by bootstrap3 that declare a dokuwiki class twice.

We don't have any issue with our bootstrap template (https://combostrap.com) or any other hogfather template.

As of today, the solution is to open an issue there and hopefully they will solved it (they got a load of issue) or to use a hogfather compliant template.

**Comment by gerardnico** [comment]
The error is described already in the issue #1 

You can just create an issue with a link to it.

Success
