### ISSUE TITLE
Doesn't work with Bootstrap3 Template

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [ComboStrap/stale#5]
In combination with Bootstrap3 Template the page structure is broken: the navbar doesn't function, and the menu of the indexmenu is no longer displayed as a structure tree

**Comment by gerardnico** [comment]
Yes, that's true. This template works only with combo.

Combo should be able to work alone but not strap.

And at the end because you will end up having css conflict, every body that uses combo install strap.

More on what strap adds as feature are described here.

https://combostrap.com/get-started/strap-template-installation-combostrap-getting-started-nuvx767h

**Comment by gerardnico** [comment]
Didn't see that it was for stale.

See #1
